version: 0.0
os: linux
files:
    - source: /
      destination: /home/ubuntu/mainproject
permissions:
    - object: /home/ubuntu
      pattern: '**'
      owner: ubuntu
      group: ubuntu
hooks:
    Beforeinstall:
      - locations: scripts/before_install.sh
        timeout: 500
        runas: ubuntu
    ApplicationStop:
      - location: scripts/application_stop.sh
        timeout: 500
        runas: ubuntu
    ApplicationStart:
      - location: scripts/application_start.sh
        timeout: 500
        runas: ubuntu
