version: 0.0
os: linux
files:
    - source: /
      destination: /home/ubuntu/mainproject
hooks:
    ApplicationStop:
        - location: scripts/application_stop.sh
          timeout: 600
          runas: ubuntu
    ApplicationStart:
        - location: scripts/application_start.sh
          timeout: 600
          runas: ubuntu
