# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    - name: zip file
      run: zip -r hous.zip ./src/scripts ./src/appspec.yml ./src/controllers ./package.json ./jest.config.js ./package-lock.json ./ecosystem.json ./tsconfig.json ./src/common ./src/config ./src/customtype ./src/interfaces ./src/middlewares ./src/models ./src/passport ./src/routes ./src/vaildation ./src/app.ts ./src/test

    - name: AWS configure credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: upload to S3
      run: aws s3 cp --region ap-northeast-2 ./hous.zip s3://btender/deploy/

    - name: deploy with AWS codeDeploy
      run: aws deploy create-deployment
        --application-name btender
        --deployment-config-name CodeDeployDefault.AllAtOnce
        --deployment-group-name btender-group
        --s3-location bucket=btender,bundleType=zip,key=deploy/hous.zip